### PR TITLE
Provide menu options for default quality of service profiles

### PR DESCRIPTION
**Pull request by pollockm**

### CODE REVIEW

**Review by dbendele — COMMENTED** [review]
do you want to remove the DDS.aliases file?

**Comment by pollockm** [comment]
I do.  My github client was being obnoxious and not removing.  I'll try again after a restart...

**Comment by pollockm** [comment]
@dbendele - Look good?

**Review by dbendele — APPROVED** [review]
glad that the user string input has been replaced by combo box. If it didn't have to be exactly "Lossy (Default)" and "Reliable", it would have made sense to have the options be parallel such as "Lossy" and "Lossless".

**Pull request merged**
